apiVersion: v1
kind: Pod
metadata:
  name: nvidia-monitor-1
spec:
  nodeName: worker1
  runtimeClassName: nvidia
  restartPolicy: Never
  containers:
  - name: nvidia-test
    image: nvcr.io/nvidia/cuda:12.5.0-base-ubuntu22.04
    command: ["/bin/bash", "-c"]
    args:
      - |
        while true; do
          echo "--- $(date) ---"
          nvidia-smi
          sleep 1
        done

---

apiVersion: v1
kind: Pod
metadata:
  name: nvidia-monitor-2
spec:
  nodeName: worker2
  runtimeClassName: nvidia
  restartPolicy: Never
  containers:
  - name: nvidia-test
    image: nvcr.io/nvidia/cuda:12.5.0-base-ubuntu22.04
    command: ["/bin/bash", "-c"]
    args:
      - |
        while true; do
          echo "--- $(date) ---"
          nvidia-smi
          sleep 1
        done

